[package]
name = "mlir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
mlir_sys = { path = "../mlir_sys" }
once_cell = "1.17.0"
