[package]
name = "circt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circt_sys = { path = "../circt_sys" }
itertools = "0.10.5"
mlir = { path = "../mlir" }
